name: Build and Push Docker Image on Release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Build and test Docker image
        run: |
          docker build -f Dockerfile -t ghcr.io/toqqaa/${{ github.event.repository.name}}:${{ github.event.release.tag_name }} .
        env:
          DOCKER_BUILDKIT: 1  # Enable BuildKit for advanced features
          
      - name: Tag Docker image as latest
        run: |
          docker tag ghcr.io/toqqaa/${{ github.event.repository.name }}:${{ github.event.release.tag_name }} ghcr.io/toqqaa/${{ github.event.repository.name }}:latest
      
      - name: Push Docker images
        run: |
          docker push ghcr.io/toqqaa/${{ github.event.repository.name}}:${{ github.event.release.tag_name }}
